### ISSUE TITLE
No clue what I'm doing

### ISSUE THREAD

**Issue by MuteTiefling** [maruohon/worldprimer#10]
Sorry, this might be better off elsewhere, but I just can't seem to get anything to work here. 

I'm trying to run some basic tests and I can't see that any of my commands are running. So I figured I'd just output a simple Say command at various points during load time... and still nothing. 

Below is my config. Am I just being silly here?
https://gist.github.com/MuteTiefling/3c00971b9d8b0561cda1343907244569

**Comment by MuteTiefling** [comment]
Well, ok I got some of the examples to work in a clean world with nothing but world primer. But I can't seem to get them to work at all in my pack that's using just enough dimensions to make new worlds...

**Comment by MuteTiefling** [comment]
Ignore me. They're working fine, except the SAY commands.

**Comment by maruohon** [comment]
The problem using the say command is that many of the command types would run the command way before the client player joins the world, meaning that you at least won't see it in your chat. So the best way is to at least look at the server console for whether or not the commands get executed. Also enabling the verbose logging option in World Primer can help while testing, because then all of the run commands will also get separately logged to the console, in case they wouldn't normally produce any output.
